#VERSION 0
;
CSY POPUP HELP
50030 "Otevírá program Sequencer. Pozmìòuje rozvrh pracovních pøíkazù a generuje  nové výrobní rozvrhy.":
50070 "Údržba tabulek dat.":
50100 "Pøesouvá data do a z Preactoru a uvolòuje rozvrhy.":
50120 "Importuje pracovní pøíkazy z jiného systému.":
50130 "Importuje zdroje z jiného systému.":
50140 "Importuje atributy výrobkù z jiného systému.":
50150 "Exportuje pracovní pøíkazy do jiného systému.":
50160 "Exportuje zdroje do jiných systémù.":
50170 "Exportuje atributy výrobkù do jiného systému.":
53020 "Vytváøí, upravuje a maže skupiny seøízení. Seskupuje výrobky do rodin, které sdílejí podobné atributy. Užívá se k urèování posloupností závislých na dobách seøízení.":
53030 "Vytváøí, upravuje a maže skupiny zdrojù. Jsou to pøirozené skupiny zdrojù, které vykonávají podrobné operace. ":
53040 "Vytváøí, upravuje a maže zdroje. Specifikuje omezení, se kterými zdroje pracují. Zakládá matice dob seøízení.":
53050 "Vytváøí, upravuje a maže sekundární omezení. Operace zavedené na zdroje mohou mít další požadavky, napøíklad na personál nebo na vybavení nástroji pøedtím, než operace mùže být zahájena.":
53100 "Pozmìòuje horizont rozvrhování, zobrazuje možnosti a posuny pro nejdøívìjší zahájení a termíny dokonèení pro nové pracovní pøíkazy. Nastavuje implicitní skripty událostí, které se mají spustit z menu pøesunù dat.":
53110 "Vytváøí, upravuje a maže podrobná data zákazníkù. Specifikuje informace o kontaktech a rovnìž tak èasy vyrovnávání dodávek.":
53510 "Vytváøí, upravuje a maže atributy výrobkù. Popisuje charakteristiky výrobkù a procesù právì používaných. Sdružuje hodnoty øazení do kategorií s atributy, které se mají použít v pøednostních posloupnostech.":
53550 "Vytváøí, upravuje a maže atributy statusù pracovních pøíkazù. Definuje vzory užívané v pruzích operací jako znázornìní statusù.":
53560 "Vytváøí, upravuje a maže atributy operací. Popisuje charaktaristiky operací výrobkù. Sdružuje hodnoty øazení do kategorií s atributy k využití pravidly rozvrhování v pøednostních posloupnostech.":
58510 "Kopíruje do jiných systémù rozvrhy pøipravené do výroby a upozoròuje ostatní, že mají k disposici nový rozvrh. ":
69100 "Varianty konfigurování, publikování a zobrazování grafù html.":
69110 "Varianty konfigurování pro PCO. Editor knihy adres a varianty  posílání a pøijímání textových hlášení.":
69120 "Varianty konfigurování pro PESP. Editor skriptù událostí, varianty definování akcí zákazníkù a nastavení èasovaných událostí.":
69130 "Varianty konfigurování pro skripty import-export. Možnosti definování a spouštìní skriptù import-export.":
69140 "Varianty konfigurací pro analýzu rozvrhù.":
;
