#VERSION 0
;
HRV POPUP HELP
50030 "Otvara sekvencer. Modificira raspored naloga i generira nove rasporede proizvodnje.":
50070 "Održavanje tablica.":
50100 "Prijenos podataka u Preactor i iz Preactora i puštanje rasporeda.":
50120 "Uvoz naloga iz drugog sustava.":
50130 "Uvoz resursa iz drugog sustava.":
50140 "Uvoz atributa proizvoda iz drugog sustava.":
50150 "Izvoz naloga u drugi sustav.":
50160 "Izvoz resursa u drugi sustav.":
50170 "Izvoza atribute proizvoda u drugi sustav.":
53020 "Kreiranje, ureðivanje i brisanje pripremih grupa. Grupiranje proizvoda koji dijele slièna svojstva. Koristi se za odreðivanje pripremnih vremena ovisnih o redosljedu.":
53030 "Kreiranje, ureðivanje i brisanje grupa resursa. To su prirodne grupe onih resursa koje mogu izvoditi sliène operacije.":
53040 "Kreiranje, ureðivanje i brisanje resursa. Specificira ogranièenja unutar kojih resurs radi. Postavlja matrice pripremnih vremena.":
53050 "Kreiranje, ureðivanje i brisanje sekundarnih ogranièenja. Operacije rasporeðene na resurs mogu imati dodatne zahtjeve (npr. osoblje ili alat) koji moraju biti zadovoljeni da bi operacija mogla zapoèeti.":
53100 "Modificiranje horizonta rasporeda, opcija prikaza i vremenskih pomaka najranijeg poèetka i roka novih naloga. Postavljanje uobièajenih skripti dogaðaja koje æe se pokretati s izbornika razmjene podataka.":
53110 "Kreiranje, ureðivanje i brisanje detalja o kupcima. Zadavanje kontakt informacija i zaštitnih vremena isporuka.":
53510 "Kreiranje, ureðivanje i brisanje atributa proizvoda. Opisuje svojstva proizvoda i korištene procese. Pridruživanje vrijednosti rangiranja atributima koje se koriste u pravilima rasporeðivanja po preferiranom redoslijedu.":
53550 "Kreiranje, ureðivanje i brisanje atributa statusa operacije. Definiranje uzoraka koji se koriste na trakama operacija za predstavljanje svakog statusa.":
53560 "Kreiranje, ureðivanje i brisanje atributa operacija. Atributi operacija opisuju karakteristike operacija proizvoda. Pridruživanje vrijednosti rangiranja atributima koje se koriste u pravilima rasporeðivanja po preferiranom redoslijedu.":
58510 "Kopira redoslijed spreman za proizvodnju u druge sustave i obaviještava ostale o dostupnosti novog rasporeda.":
69100 "Opcije za konfiguriranje, objavu i pregled html dijagrama.":
69110 "Konfiguracijske opcije za PCO. Ureðivaè adresara i opcija slanja i primanja tekstualnih poruka.":
69120 "Konfiguracijske opcije za PESP. Ureðivaè skripti dogaðaja, opcija za definiranje korisnièkih akcija i postavki vremenskih dogaðaja.":
69130 "Konfiguracijske opcije uvozno-izvoznih skripti. Opcije za definiranje i izvoðenje uvozno-izvoznih skripti.":
69140 "Konfiguracijske opcije analize rasporeda.":
;
