#VERSION 0
;
HUN POPUP HELP
50030 "A sorrendvezérlõ megnyitása, amellyel módosíthatja a rendelések ütemezését, illetve új termelési ütemezéseket hozhat létre.":
50070 "Adatbázistáblák karbantartása.":
50100 "Adatok átvitele a Preactor alkalmazásba, illetve exportálása az alkalmazásból, illetve az ütemezés megjelentetése.":
50120 "Rendelések importálása egy másik rendszerbõl.":
50130 "Erõforrások importálása egy másik rendszerbõl.":
50140 "Termékattribútumok importálása egy másik rendszerbõl.":
50150 "Rendelések exportálása egy másik rendszerbe.":
50160 "Erõforrások exportálása egy másik rendszerbe.":
50170 "Termékattribútumok exportálása egy másik rendszerbe.":
53020 "Beállítási csoportok létrehozása, módosítása és törlése. A termékeket a hasonló attribútumok alapján családokba rendezheti. Ez a sorrendfüggõ beállítási idõk meghatározására szolgál.":
53030 "Erõforráscsoportok létrehozása, módosítása és törlése. Ezek a hasonló mûveletek elvégzésére alkalmas erõforrások természetes csoportjai.":
53040 "Erõforrások létrehozása, módosítása és törlése. Határozza meg az erõforrások mûködését szabályozó megkötéseket. Állítsa be az idõmátrixokat.":
53050 "Másodlagos megkötések létrehozása, módosítása és törlése. Az erõforrásokra betöltött mûveletekhez gyakran további (például dolgozókra vagy eszközökre vonatkozó) követelmények társulnak, amelyeknek teljesülnie kell, hogy a mûvelet megkezdõdhessen.":
53100 "Az ütemezési horizont módosítása, az új rendelésekre vonatkozó legkorábbi kezdési dátum, illetve határidõ eltolásának és beállításainak megjelenítése. Állítsa be az alapértelmezés szerint futtatandó esemény-parancsprogramokat az Adatátvitel menüben.":
53110 "Ügyféladatok létrehozása, módosítása és törlése. Adja meg a kapcsolatfelvételi adatokat, valamint a szállítási puffer idõtartamát.":
53510 "Termékattribútumok létrehozása, módosítása és törlése. Írja le a használt termékek és folyamatok jellemzõit. Társítson rangsorolási értékeket az attribútumokhoz a preferált sorrend ütemezésére szolgáló szabályok számára.":
53550 "Rendelésistátusz-attribútumok létrehozása, szerkesztése és törlése. Határozza meg a mûveleti sávokban az egyes státuszok jelzésére használt mintákat.":
53560 "Mûveletattribútumok létrehozása, módosítása és törlése. Írja le a termékhez kapcsolódó mûveletek jellemzõit. Társítson rangsorolási értékeket az attribútumokhoz a preferált sorrend ütemezésére szolgáló szabályok számára.":
58510 "Az üzemkész ütemezések más rendszerekre másolása, illetve a többi felhasználó értesítése az új elérhetõ ütemezésrõl.":
69100 "A HTML-diagramok konfigurálására, közzétételére és megtekintésére szolgáló lehetõségek.":
69110 "A PCO beállításai. Címtárszerkesztõ, illetve a szöveges üzenetek küldésére és fogadására szolgáló lehetõségek.":
69120 "A PESP beállításai. Esemény-parancsprogramok szerkesztõje, az egyéni mûveletek, illetve az idõzített események beállításainak meghatározására szolgáló lehetõségek.":
69130 "Az importálási/exportálási parancsprogramok konfigurációs lehetõségei. Az importálási/exportálási parancsprogramok létrehozására, illetve futtatására szolgáló lehetõségek.":
69140 "Az Ütemezéselemzés funkció konfigurációs lehetõségei.":
;
