#VERSION 0
;
SKY POPUP HELP
50030 "Otvorenie plánovaèa. Modifikácia plánu objednávok a generovanie nového vırobného plánu.":
50070 "Údrba dátovıch tabuliek.":
50100 "Prenos dát do/z Preactora a uvo¾nenie plánu.":
50120 "Import objednávok z iného systému.":
50130 "Imports resources from another system.":
50140 "Imports product attributes from another system.":
50150 "Export objednávok z iného systému.":
50160 "Exports resources to another system.":
50170 "Exports product attributes to another system.":
53020 "Vytvorenie, editovanie a vımaz setup skupín. Zoskupenie vırobkov do rodín, ktoré zdielajú podobné vlastnosti. Pouité pre urèenie nastavovacích èasov závislıch od poradia.":
53030 "Vytvorenie, editovanie a vımaz skupín zdrojov. Toto sú prirodzené supiny zdrojov, ktoré môu vykonáva podobné operácie.":
53040 "Vytvorenie, editovanie a vımaz zdrojov. Urèenie obmedzení v operáciách. Vytvorenie matice nastavovacích èasov.":
53050 "Vytvorenie, editovanie a vımaz sekundárnych obmedzení. Operácie pouívajúce zdroje môu ma dodatoèné poiadavky, napríklad personál alebo náradie, skôr ako operácia zaène.":
53100 "Modifikácia plánovacieho horizontu, zobrazenie moností a odchıliek pre najskorší zaèiatok a dátum ukonèenia pre nové objednávky. Nastavenie preddefinovaného scriptu udalostí ktorı by mal by spustenı z menu Prenosu dát.":
53110 "Vytvorenie, editovanie a vımaz podrobností o zákazníkoch . Urèenie kontaktnıch informácií ako aj zásobníka dodacích èasov.":
53510 "Vytvorenie, editovanie a vımaz atribútov vırobkov. Popisuje vlastnosti pouitıch vırobkov a postupov. Spájanie kategorizaènıch hodnôt do atribútov pouitıch v pravidlách preferovaného poradia plánovania.":
53550 "Vytvorenie, editovanie a vımaz atribútov stavov objednávok. Definuje zobrazenie pouité v lištách operácií pre vyjadrenie stavov.":
53560 "Vytvorenie, editovanie a vımaz atribútov operácií. Popis vlastností operácií vırobku. Spájanie kategorizaènıch hodnôt do atribútov pouitıch v pravidlách preferovaného poradia plánovania.":
58510 "Kopírovanie  plánu pripraveného pre vırobu do inıch systémov a upozornenie ostatnıch na dostupnos nového plánu.":
69100 "Monosti konfigurácie, prezentovanie a zobrazenie html diagramov.":
69110 "Vo¾by Konfigurácie PCO. Editor Knihy Adries a vo¾by pre posielanie a prijímanie textovıch správ.":
69120 "Vo¾by Konfigurácie PESP. Editor scriptu udalostí, vo¾by definujúce pouívate¾ské akcie a nastavenia pre èasované udalosti.":
69130 "Vo¾by Konfigurácie pre import-export scripty. Vo¾by pre definovanie a beh import-export scriptov.":
69140 "Vo¾by Konfigurácie pre Analızy Plánu.":
;
