#VERSION 0
;
TRK POPUP HELP
50030 "Sýralayýcýyý açar. Sipariþlerin çizelgesini deðiþtir ve yeni üretim çizelgeleri oluþtur.":
50070 "Veri tablolarýný koru.":
50100 "Preactor'dan veri al ve gönder ve çizelgeyi serbest býrak.":
50120 "Sipariþleri bir baþka sistemden dýþtan al.":
50130 "Imports resources from another system.":
50140 "Imports product attributes from another system.":
50150 "Sipariþerli bir baþka sisteme dýþa gönder.":
50160 "Exports resources to another system.":
50170 "Exports product attributes to another system.":
53020 "Ayar gruplarýný oluþtur, düzenle ve sil. Ürünleri ayný nitelikleri paylaþan ailelere gruplandýr. Sýraya dayalý ayar zamanlarýný belirlemek için kullanýlýr.":
53030 "Kaynak gruplarýný oluþtur, düzenle ve sil. Bunlar benzer operasyonlarý iþleyebilen doðal kaynak gruplarýdýr. ":
53040 "Kaynaklarý oluþtur, düzenle ve sil. Kaynaklarýn çalýþtýðý kýsýtlarý belirle. Ayar matrislerini kur. ":
53050 "Ýkincil kýsýtlarý oluþtur, düzenle ve sil. Kaynaklara yüklenen operasyonlarýn ek gereksinimleri olabilir, örneðin personel veya takýmlarýn operasyon baþlamadan gerekmesi.":
53100 "Yeni sipariþler için çizelge ufku, görüntüleme seçenekleri ve en erken baþlama ve teslim tarihleri dengelemerini deðiþtirin. Veri Transfer Menüsünden çalýþtýrýlacak varsayýlan olay betiklerini  yerleþtirin. ":
53110 "Müþteri detaylarýný oluþtur, düzenle ve sil. Ýletiþim bilgilerini ve teslimat tampon sürelerini belirleyin.":
53510 "Ürün niteliklerini oluþtur, düzenle ve sil. Ürün karateristiklerini ve ve kullanýlan prosesleri tanýmlayýn. Tercihli sýralý çizelgeleme kurallarý tarafýndan kullanýlacak  sýralama deðerlerini niteliklere iliþkilendir.":
53550 "Sipariþ durumu niteliklerini oluþtur, düzenle ve sil. Operasyon  çubuklarýnýn üzerinde her durum için kullanýlan desenleri tanýmla.":
53560 "Operasyon niteliklerini oluþtur, düzenle ve sil. Bir ürünün operasyonlarýnýn karakteristiklerini tanýmla. Tercihli sýralý çizelgeleme kurallarý tarafýndan kullanýlacak  sýralama deðerlerini niteliklere iliþkilendir.":
58510 "Üretime hazýr bir çizelgeyi diðer sistemlere kopyalar ve diðerlerine yeni bir çizelgenin hazýr olduðunu bildirir.":
69100 "html grafikleri konfigüre etmek, yayýmlamak ve göstermek için seçenekler.":
69110 "PCO için konfigürasyon seçenekleri. Mesaj göndermek ve almak için adres defteri düzenleyicisi ve seçenekleri.":
69120 "PESP için konfigürasyon seçenekleri. Kiþiselleþtirilmiþ eylemler ve zamanlý olay ayarlarý için olay betik düzenleyicisi, seçenekleri.":
69130 "Import\Export Scriptleri için konfigürasyon seçenekleri. Dýþtan alma-Dýþa gönderme betiklerini tanýmlamak ve çalýþtýrmak için seçenek. ":
69140 "Çizelgeleme Analizi için konfigürasyon seçenekleri. ":
;
