#VERSION 0
;
PTG POPUP HELP
50030 "Abre o sequenciador. Modifica a programação das ordens e gera um novo sequenciamento. ":
50070 "Cadastros de informações básicas.":
50100 "Transfere dados e libera a programação para execução.":
50120 "Importa ordens de outro sistema.":
50130 "Importa recursos de outros sistema. ":
50140 "Importa atributos de produtos de outro sistema":
50150 "Exporta ordens para outro sistema.":
50160 "Exporta recursos para outro sistema":
50170 "Exporta atributos de produtos para outro sistema. ":
53020 "Cria, edita e exclui Grupos de Setups. Agrupa produtos que compartilham atributos similares em famílias. Usado para determinar setups dependentes de sequência.":
53030 "Cria, edita e exclui Grupos de Recursos. Estes são os grupos de Recursos que podem realizar operações similares.":
53040 "Cria, edita e exclui Recursos. Especifica as restrições em que esses Recursos operam. Estabelece matrizes de Setup.":
53050 "Cria, edita ou exclui Recursos Secundários. Operações carregadas em Recursos podem ter requerimentos adicionais, como exemplo, pessoas ou ferramentas que são necessárias antes da operação iniciar.":
53100 "Modifica o horizonte de programação, exibe opções para data de início mais cedo e data de entrega para ordens novas. Define o script de evento padrão que será executado a partir do menu de Integração.":
53110 "Cria, edita e exclui detalhes do Cliente. Especifica informações de contato bem como prazos de entrega.":
53510 "Cria, edita e exclui atributos de produto. Descreva as características dos produtos e os processos que são utilizados. Associe valores do Rank desses atributos para serem usados na regra APS Sequência Preferida":
53550 "Cria, edita e exclui Atributos do Status da Ordem. Define o padrão usado na barra de operação para representar cada status.":
53560 "Cria, edita e exclui Atributos da Operação. Descreve características das operações do produto. Associa valores do Rank nesses atributos para serem usados na regra APS Sequência Preferida.":
58510 "Copia uma programação de produção pronta para outro sistema e notifica que uma nova programação está disponível.":
69100 "Opções para configurar, publicar e visualizar gráficos HTML.":
69110 "Opções de configuração para PCO. Editor de lista de endereços e opções para enviar e receber mensagens de texto.":
69120 "Opções de configuração para PESP. Editor de scripts de eventos, opções para definir ações personalizadas e definições de Eventos de Calendário.":
69130 "Opções de configuração para scripts de importação/exportação e opções para definir e executar scripts de importação/exportação.":
69140 "Opções de configuração para a Análise do Sequenciamento.":
;
