#VERSION 0
;
PLK POPUP HELP
50030 "Otwiera generator harmonogramu. Zmodyfikuj harmonogram zleceñ i utwórz nowe harmonogramy produkcji.":
50070 "Obs³uga bazy danych.":
50100 "Przeœlij dane do systemu Preactor i pobierz dane z systemu oraz udostêpnij harmonogram.":
50120 "Importuje zlecenia z innego systemu.":
50130 "Importuje zasoby z innego systemu.":
50140 "Importuje atrybuty produktu z innego systemu.":
50150 "Eksportuje zlecenia do innego systemu.":
50160 "Eksportuje zasoby do innego systemu.":
50170 "Eksportuje atrybuty produktu do innego systemu.":
53020 "Twórz, edytuj i usuwaj grupy przezbrojeñ. Grupuj produkty do postaci rodzin dziel¹cych podobne atrybuty. S³u¿y do okreœlenia czasów przezbrojeñ zale¿nych od kolejnoœci.":
53030 "Twórz, edytuj i usuwaj grupy zasobów. S¹ to naturalne grupy zasobów, które zapewniaj¹ wykonywanie podobnych operacji.":
53040 "Twórz, edytuj i usuwaj zasoby. Okreœl ograniczenia dzia³ania zasobów. Ustaw formaty okresu konfiguracji.":
53050 "Twórz, edytuj i usuwaj ograniczenia drugorzêdowe. Operacje przydzielone do zasobów mog¹ zawieraæ dodatkowe ograniczenia, np. dot. osób lub narzêdzi wymaganych przed rozpoczêciem operacji.":
53100 "Modyfikuj horyzont planowania, wyœwietlaj opcje i przesuniêcia w przypadku najwczeœniejszych dat rozpoczêcia i terminów realizacji zleceñ. Ustaw domyœlne skrypty zdarzeñ uruchamiane z poziomu menu transferu danych.":
53110 "Twórz, edytuj i usuwaj detale klientów. Okreœl informacje kontaktowe oraz marginesy czasowe dostaw.":
53510 "Twórz, edytuj i usuwaj atrybuty produktów. Opisuj charakterystyki produktów i u¿ywane procesy. £¹cz wartoœci rangi z atrybutami z przeznaczeniem do u¿ywania przez preferowane regu³y planowania harmonogramowanie.":
53550 "Twórz, edytuj i usuwaj atrybuty statusu zlecenia. Definiuj szyki u¿ywane na paskach operacji w celu reprezentowania ka¿dego statusu.":
53560 "Twórz, edytuj i usuwaj atrybuty operacji. Opisuj charakterystyki operacji w przypadku produktów. £¹cz wartoœci rangi z atrybutami z przeznaczeniem do u¿ywania przez preferowane regu³y planowania harmonogramowanie.":
58510 "Kopiuje harmonogram gotowy do produkcji do innych systemów i powiadamia inne osoby o dostêpnoœci nowego harmonogramu.":
69100 "Opcje konfiguracji, publikowania i wyœwietlania wykresów html.":
69110 "Opcje konfiguracji dla PCO. Edytor ksi¹¿ki adresowej i opcje wysy³ania i odbierania wiadomoœci tekstowych.":
69120 "Opcje konfiguracji dla PESP. Edytor skryptów zdarzeñ i opcje definiowania czynnoœci niestandardowych oraz ustawienia zdarzeñ zaplanowanych.":
69130 "Opcje konfiguracji zwi¹zane ze skryptami importowania i eksportowania. Opcja definiowania i uruchamiania skryptów importowania i eksportowania.":
69140 "Opcje konfiguracji analizy harmonogramu.":
;
